### ISSUE TITLE
Review of recent pull #19

### ISSUE THREAD

**Issue by gregallensworth** [greeninfo/Mobile-ClevelandMetroparks#18]
Review of changes as described in https://github.com/greeninfo/Mobile-ClevelandMetroparks/pull/17

* Welcome panel has Skip button commented out
* Keyword search, change from Text to Search which changes other behaviors
* bignoodletitling/specimen_files/ is demo for the theme? extraneous?

Reported outstanding issues possibly pertaining to these changes:
* keyword search: changed to Search from Text, hoping to obviate need for a submit button; apparently on typing it brings up some other button?
* results pages - check current styling and generate list of CSS classes for Adam to continue work. Give him specimens for both plain lists (POIs) and ones with additional info (Trail Finder, has smaller text).
* Loading spinner has a boxy border around it; is this intentional?

**Comment by gregallensworth** [comment]
*Keyword search*
I reprogrammed this to work without the Search button. Commit 303079c

Outstanding issue: The text input is not 100% width like the rest of the page, so it looks off-center.

Outstanding issue: The new theme apparently won't heed data-icon="search" to decorate the text box with a magnifying glass. May want to modify the theme to add this decoration if it is desired. The type="search" has the magnifying glass, but is not intended to function as a text input for this sort of search.

**Comment by gregallensworth** [comment]
*Welcome panel*

Confirmed that the welcome panel is now only accessible from  the "About This App" on the map settings. Now that the "Show This Next Time" checkbox is gone, is it never checked and so there is no way for a user to set this preference.

Please clarify intended behavior here:
* Should the Welcome panel always show,
* or should it never show by default, and be solely accessible from the Settings panel (really an About page, not a Welcome page)?

If there is no need for it to automatically show ever again, I can remove some storage code pertaining to the checkbox preference, etc.

**Comment by gregallensworth** [comment]
*Results Panels*

The result listing is a UL element with special "listview" jQuery Mobile handling and some CSS to make it wide except for the inset box,e c.

Each result entry is represented with a LI element within that UL.
It has these classes:
ui-li ui-li-static ui-body-c ui-li-has-count

This LI has a single child element and no other content. This DIV is the text content, and has these classes:
ui-btn-text

The title text within this LI is a SPAN element with one class:    ui-li-heading
Smaller text is a SPAN element with class:    ui-li-desc
You may have as many of these two types of SPAN element as you wish, though I'd suggest only one title.

Distance readouts are SPAN elements with the following classes:
zoom_distance ui-li-count ui-btn-up-c ui-btn-corner-all
I recommend modifying the zoom_distance instead of the other classes, since this is the not specific to these distance readouts, and has the least potential to affect other elements.

**Comment by gregallensworth** [comment]
*Navigation Buttons*

Their styling is inconsistent when I click on them. The theme should have some :active classes, or at least override the :active behavior, so that the buttons do not change color and font and size a they are clicked.

**Comment by greeninfo** [comment]
Update: pulled pull request #19 for review.
