### ISSUE TITLE
Map panel, bottom bar

### ISSUE THREAD

**Issue by gregallensworth** [greeninfo/Mobile-ClevelandMetroparks#8]
The bottom bar, on the map panel: intent is to rework this with new icons, a new color to match either the green or the brown. Designs are still in the works.

**Comment by gregallensworth** [comment]
Commit 4509dac adds some of these icons, though a few are still missing.

**Comment by greeninfo** [comment]
Bump. Still need for map bottom bar:
- Settings button
- Nearby icon size checked or aproved as-is

**Comment by greeninfo** [comment]
New settings button in place, per commit 4d73d06

**Comment by greeninfo** [comment]
Commit 86792de has the final version of the bottom-bar buttons for the Map panel.

Case closed.
