### ISSUE TITLE
Changes to offline tile-saving behavior

### ISSUE THREAD

**Issue by gregallensworth** [greeninfo/Mobile-ClevelandMetroparks#9]
New behavior proposed for offline tiles:

- Do not use the loading spinner. It stays visible and is confusing: some think that they cannot use the app, other use the app but find it annoying. (Worst of both worlds!)

- Have a message indicating that they'll be notified when it's done. (modal? on-panel?)

- On complete, make a modal telling them that their download has completed.

**Comment by gregallensworth** [comment]
Thinking out a potential usability question: If someone tries to download multiple items simultaneously (pan to new viewport, pick another reservation), it should work... but may become confusing if it says "Your download is done" and they don't know which one.

Can download processes be tagged with a name and that given?
Perhaps better to simply allow only one download at a time, detect that one is in progress and refuse? Definitely easier to do in time available, and bypasses other potential issues such as saturating the device with 5 reservation download tasks.

**Comment by gregallensworth** [comment]
Commit  cb17532 addresses all of this: new workflow, dedicated and single Progress page, nice progress bar, ... Pretty sweet.

Also bypasses the "which of the N downloads is it?" question: only one download happens at a time, since the Settings panel will show EITHER the seeding links OR ELSE the progress link.

**Comment by greeninfo** [comment]
Tile lists given by client were incorrect, using TMS URLs instead of Google Webmerc URLs. Re-opening for new tile lists.

**Comment by greeninfo** [comment]
Completed by commit bd9b00e
